name: spotify_music_helper
description: "Move/Add/Remove multiple songs in a playlist."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 3.0.0+6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  get: ^4.6.6
  another_flushbar: ^1.12.30
  audioplayers: ^5.2.1
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 1.2.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.13.2
  flutter_cache_manager: ^3.3.1
  firebase_analytics: ^10.8.5
  flutter_secure_storage: ^9.0.0
  google_mobile_ads: ^4.0.0
  firebase_auth: ^4.17.4

  intl: any
  flutter_native_splash: ^2.3.10
  firebase_app_check: ^0.2.1+15
  flutter_launcher_icons: ^0.13.1
  firebase_crashlytics: ^3.4.16
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
