// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4gISTDhNhOXC3FMMaKgfjnX5mMLnBFso',
    appId: '1:662074339029:web:e1b68f53050db503cabc5c',
    messagingSenderId: '662074339029',
    projectId: 'spot-helper-1688d',
    authDomain: 'spot-helper-1688d.firebaseapp.com',
    storageBucket: 'spot-helper-1688d.appspot.com',
    measurementId: 'G-N80B94TF0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf9B1pjHVck7ZuQW2kXRkRLMpkw7i75eg',
    appId: '1:662074339029:android:bfa23f10c92738b0cabc5c',
    messagingSenderId: '662074339029',
    projectId: 'spot-helper-1688d',
    storageBucket: 'spot-helper-1688d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjbPnzsgBFATdBKedc5_6I6_HGMomWyM',
    appId: '1:662074339029:ios:618c3d6a61c11648cabc5c',
    messagingSenderId: '662074339029',
    projectId: 'spot-helper-1688d',
    storageBucket: 'spot-helper-1688d.appspot.com',
    iosBundleId: 'com.example.musicSwapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPjbPnzsgBFATdBKedc5_6I6_HGMomWyM',
    appId: '1:662074339029:ios:74fcef567dec84f5cabc5c',
    messagingSenderId: '662074339029',
    projectId: 'spot-helper-1688d',
    storageBucket: 'spot-helper-1688d.appspot.com',
    iosBundleId: 'com.example.musicSwapper.RunnerTests',
  );
}
